services:
  # The MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senior_project_2026
      MYSQL_DATABASE: eadvisor_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # Bridges your local files to the Database's folder
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

  # The Node.js Backend
  server:
    build: ./server
    container_name: eadvisor_backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - PORT=5000
      - DB_HOST=db
      - DB_PASSWORD=senior_project_2026
    volumes:
      # Syncs your VS Code folder with the Docker folder in real-time!
      - ./server:/app
      - /app/node_modules

# This creates a safe "Storage Bin" for your database data
volumes:
  mysql_data: